import type { SemanticIconDefinition } from "./types.js";

const define = (
  name: string,
  nerdFont: string,
  unicode: string,
  ascii: string,
  categories: readonly string[],
  aliases: readonly string[] = [],
): SemanticIconDefinition => ({
  name,
  nerdFont,
  unicode,
  ascii,
  categories,
  aliases,
  label: name.replaceAll("-", " "),
});

export const semanticIcons = [
  // ── Arrows ──────────────────────────────────────────────────────────────
  define("arrow-up", "nf-md-arrow-up", "↑", "^", ["arrows", "navigation"]),
  define("arrow-down", "nf-md-arrow-down", "↓", "v", ["arrows", "navigation"]),
  define("arrow-left", "nf-md-arrow-left", "←", "<", ["arrows", "navigation"]),
  define("arrow-right", "nf-md-arrow-right", "→", ">", ["arrows", "navigation"]),
  define("arrow-up-right", "nf-md-arrow-top-right", "↗", ">^", ["arrows"], ["external-link"]),
  define("arrow-down-right", "nf-md-arrow-bottom-right", "↘", ">v", ["arrows"]),
  define("arrow-up-left", "nf-md-arrow-top-left", "↖", "<^", ["arrows"]),
  define("arrow-down-left", "nf-md-arrow-bottom-left", "↙", "<v", ["arrows"]),
  define("chevron-up", "nf-md-chevron-up", "⌃", "^^", ["arrows"]),
  define("chevron-down", "nf-md-chevron-down", "⌄", "vv", ["arrows"]),
  define("chevron-left", "nf-md-chevron-left", "⟨", "<<", ["arrows"]),
  define("chevron-right", "nf-md-chevron-right", "⟩", ">>", ["arrows"]),
  define("chevrons-up", "nf-md-chevron-double-up", "⇈", "^^", ["arrows"]),
  define("chevrons-down", "nf-md-chevron-double-down", "⇊", "vv", ["arrows"]),
  define("chevrons-left", "nf-md-chevron-double-left", "⇇", "<<", ["arrows"]),
  define("chevrons-right", "nf-md-chevron-double-right", "⇉", ">>", ["arrows"]),
  define("corner-up-left", "nf-md-arrow-top-left-bottom-right", "⌜", "<^", ["arrows"]),
  define("corner-up-right", "nf-md-arrow-top-right-bottom-left", "⌝", "^>", ["arrows"]),
  define("corner-down-left", "nf-md-arrow-bottom-left", "↲", "<v", ["arrows"]),
  define("corner-down-right", "nf-md-arrow-bottom-right", "↳", "v>", ["arrows"]),
  define("refresh-cw", "nf-md-refresh", "↻", "@@", ["arrows", "actions"], ["reload"]),
  define("refresh-ccw", "nf-md-restart", "↺", "@", ["arrows", "actions"], ["undo-all"]),
  define("rotate-cw", "nf-md-rotate-right", "↷", "ro>", ["arrows", "actions"]),
  define("rotate-ccw", "nf-md-rotate-left", "↶", "ro<", ["arrows", "actions"]),

  // ── Navigation ──────────────────────────────────────────────────────────
  define("compass", "nf-md-compass", "◎", "C", ["navigation"]),
  define("map", "nf-md-map", "◫", "[M]", ["navigation"]),
  define("map-pin", "nf-md-map-marker", "⚑", "o>", ["navigation"], ["location", "pin", "marker"]),
  define("navigation", "nf-md-navigation", "➢", ">", ["navigation"], ["navigate", "direction"]),
  define("locate", "nf-md-crosshairs-gps", "⊕", "(+)", ["navigation"], ["crosshair", "gps"]),
  define("crosshair", "nf-md-crosshairs", "⊕", "+", ["navigation", "gaming"], ["target"]),
  define("globe", "nf-md-web", "●", "O", ["navigation", "communication"]),
  define("link", "nf-md-link", "⛓", "~~", ["navigation", "actions"], ["url", "hyperlink"]),
  define("link-off", "nf-md-link-off", "⟎", "~~x", ["navigation"], ["unlink", "unlinked"]),
  define("external-link", "nf-md-open-in-new", "⇱", "->>", ["navigation", "actions"]),

  // ── Actions ─────────────────────────────────────────────────────────────
  define("copy", "nf-md-content-copy", "⎘", "cp", ["actions", "files"], ["duplicate"]),
  define("clipboard", "nf-md-clipboard", "▦", "[]", ["actions", "files"]),
  define("clipboard-check", "nf-md-clipboard-check", "▦✓", "[]+", ["actions", "files"]),
  define("clipboard-list", "nf-md-clipboard-list", "▦≡", "[]=", ["actions", "files"]),
  define("clipboard-copy", "nf-md-clipboard-multiple", "▦⎘", "[]c", ["actions", "files"]),
  define("scissors", "nf-md-content-cut", "✂", "x>", ["actions", "design"], ["cut"]),
  define("paste", "nf-md-clipboard-plus", "▦+", "cp+", ["actions"]),
  define("undo", "nf-md-undo", "↩", "<-", ["actions"]),
  define("redo", "nf-md-redo", "↪", "->", ["actions"]),
  define("zoom-in", "nf-md-magnify-plus", "⌕+", "+Z", ["actions"], ["magnify-in"]),
  define("zoom-out", "nf-md-magnify-minus", "⌕-", "-Z", ["actions"], ["magnify-out"]),
  define("filter", "nf-md-filter", "▽", "F", ["actions"], ["funnel"]),
  define("sliders", "nf-md-tune", "⫼", "==", ["actions"], ["adjust", "tune"]),
  define("sort-asc", "nf-md-sort-ascending", "△", "A>", ["actions"]),
  define("sort-desc", "nf-md-sort-descending", "▽", "Z>A", ["actions"]),
  define("sort", "nf-md-sort", "⇅", "<>", ["actions"]),
  define("layers", "nf-md-layers", "▤", "[[]]", ["actions", "design"]),
  define("archive", "nf-md-archive", "⍟", "[]v", ["actions", "files"], ["box"]),
  define("crop", "nf-md-crop", "⊞", "[]|", ["actions", "design"]),
  define("move", "nf-md-arrow-all", "⤡", "~>", ["actions"], ["drag"]),
  define("maximize", "nf-md-arrow-expand", "⤢", "[]", ["actions", "arrows"], ["expand"]),
  define("minimize", "nf-md-arrow-collapse", "⤡", "_", ["actions", "arrows"], ["collapse", "shrink"]),
  define("fullscreen", "nf-md-fullscreen", "⊠", "[]", ["actions"], ["expand-screen"]),
  define("qr-code", "nf-md-qrcode", "▧", "QR", ["actions", "commerce"]),
  define("barcode", "nf-md-barcode", "∣∣", "||", ["actions", "commerce"]),
  define("magnet", "nf-md-magnet", "⏻", "U", ["actions", "science"]),

  // ── Status ──────────────────────────────────────────────────────────────
  define("check", "nf-md-check", "✓", "+", ["actions", "status"], ["success", "done"]),
  define("check-circle", "nf-md-check-circle", "○✓", "(+)", ["status"], ["success-circle"]),
  define("x-circle", "nf-md-close-circle", "○×", "(x)", ["status"], ["close-circle", "cancel-circle"]),
  define("alert-circle", "nf-md-alert-circle", "○▲", "(!)", ["status"], ["warning-circle"]),
  define("info-circle", "nf-md-information-outline", "○ⓘ", "(i)", ["status"]),
  define("question-mark-circle", "nf-md-help-circle", "○?", "(?)", ["status"], ["help-circle"]),
  define("plus-circle", "nf-md-plus-circle", "○+", "(+)", ["status", "math"], ["add-circle"]),
  define("minus-circle", "nf-md-minus-circle", "○−", "(-)", ["status", "math"], ["remove-circle"]),
  define("close", "nf-md-close", "×", "x", ["actions", "status"], ["cancel"]),
  define("warning", "nf-md-alert", "▲", "!", ["status"], ["alert"]),
  define("info", "nf-md-information", "ⓘ", "i", ["status"]),
  define("help", "nf-md-help-circle", "?", "?", ["status"], ["question"]),
  define("plus", "nf-md-plus", "+", "+", ["actions"], ["add", "create"]),
  define("minus", "nf-md-minus", "−", "-", ["actions"], ["remove"]),
  define("star", "nf-md-star-outline", "☆", "*", ["status"], ["favorite", "bookmark-star"]),
  define("star-filled", "nf-md-star", "★", "*", ["status"], ["starred", "favorite-filled"]),
  define("heart", "nf-md-heart-outline", "♡", "<3", ["status"], ["like", "favorite"]),
  define("heart-filled", "nf-md-heart", "♥", "<3", ["status"], ["liked", "favorite-filled"]),
  define("thumbs-up", "nf-md-thumb-up-outline", "☑", "+1", ["status"], ["like-up"]),
  define("thumbs-down", "nf-md-thumb-down-outline", "☒", "-1", ["status"], ["like-down"]),
  define("bookmark", "nf-md-bookmark-outline", "⌘", ">", ["status", "actions"], ["save"]),
  define("bookmark-filled", "nf-md-bookmark", "⌘", ">>", ["status", "actions"], ["saved"]),
  define("flag", "nf-md-flag-outline", "⚐", ">", ["status", "gaming"], ["report"]),
  define("flag-filled", "nf-md-flag", "⚑", ">>", ["status", "gaming"]),
  define("zap", "nf-md-lightning-bolt", "⚡", "~>", ["status"], ["lightning", "fast", "flash"]),
  define("sparkles", "nf-md-star-four-points", "✨", "**", ["status"], ["stars", "magic"]),

  // ── Media ───────────────────────────────────────────────────────────────
  define("play", "nf-md-play", "▶", ">", ["media", "actions"], ["start", "resume"]),
  define("pause", "nf-md-pause", "Ⅱ", "||", ["media", "actions"]),
  define("stop", "nf-md-stop", "■", "[]", ["media", "actions"]),
  define("skip-forward", "nf-md-skip-next", "≫", ">|", ["media"], ["next"]),
  define("skip-back", "nf-md-skip-previous", "≪", "|<", ["media"], ["previous"]),
  define("forward", "nf-md-fast-forward", "≫≫", ">>", ["media"]),
  define("rewind", "nf-md-rewind", "≪≪", "<<", ["media"]),
  define("shuffle", "nf-md-shuffle", "⇄", "~>", ["media"]),
  define("repeat", "nf-md-repeat", "↻", "@", ["media", "actions"]),
  define("volume", "nf-md-volume-medium", "◓", "))", ["media", "devices"], ["sound-level"]),
  define("volume-high", "nf-md-volume-high", "◖", ")))", ["media", "devices"], ["sound"]),
  define("volume-mute", "nf-md-volume-mute", "◗", "x)", ["media", "devices"], ["mute", "muted"]),
  define("volume-off", "nf-md-volume-off", "×", "x", ["media", "devices"]),
  define("microphone", "nf-md-microphone", "◉", "O)", ["media", "devices"], ["mic"]),
  define("headphones", "nf-md-headphones", "♫", "o)", ["media", "devices"], ["headset"]),
  define("speaker", "nf-md-speaker", "⍾", "O)", ["media", "devices"]),
  define("music", "nf-md-music", "♪", "*", ["media", "music"], ["song"]),
  define("music-note", "nf-md-music-note", "♫", "**", ["media", "music"]),
  define("playlist", "nf-md-playlist-music", "≋", "=", ["media", "music"], ["queue"]),
  define("radio", "nf-md-radio", "⊚", "R", ["media", "devices"]),

  // ── Files ───────────────────────────────────────────────────────────────
  define("file", "nf-md-file", "□", "[F]", ["files"]),
  define("file-text", "nf-md-file-document", "≡□", "[T]", ["files"]),
  define("file-code", "nf-md-file-code", "◇", "</>", ["files", "development"], ["code-file"]),
  define("file-image", "nf-md-file-image", "⊡", "[I]", ["files"]),
  define("file-video", "nf-md-file-video", "▶□", "[V]", ["files"]),
  define("file-audio", "nf-md-file-music", "♫□", "[A]", ["files"], ["file-music"]),
  define("file-archive", "nf-md-zip-box", "▦", "[Z]", ["files"], ["zip", "archive-file"]),
  define("file-plus", "nf-md-file-plus", "+□", "[+F]", ["files"]),
  define("file-minus", "nf-md-file-minus", "−□", "[-F]", ["files"]),
  define("file-check", "nf-md-file-check", "✓□", "[✓F]", ["files"]),
  define("file-x", "nf-md-file-remove", "×□", "[xF]", ["files"]),
  define("file-lock", "nf-md-file-lock", "⏽□", "[LF]", ["files"]),
  define("folder", "nf-md-folder", "▣", "[D]", ["files"]),
  define("folder-open", "nf-md-folder-open", "▤", "[D]", ["files"]),
  define("folder-plus", "nf-md-folder-plus", "▣+", "[D+]", ["files"]),
  define("folder-check", "nf-md-folder-check", "▣✓", "[D✓]", ["files"]),
  define("folder-x", "nf-md-folder-remove", "▣×", "[Dx]", ["files"]),
  define("folder-tree", "nf-md-file-tree", "├▣", "|-", ["files"]),
  define("edit", "nf-md-pencil", "✎", "~", ["actions"], ["pencil"]),
  define("trash", "nf-md-delete", "⌫", "x", ["actions", "files"], ["delete", "bin"]),
  define("trash-2", "nf-md-trash-can", "⌫", "xx", ["actions", "files"], ["delete-forever"]),
  define("download", "nf-md-download", "↓", "v", ["actions", "files"]),
  define("upload", "nf-md-upload", "↑", "^", ["actions", "files"]),
  define("save", "nf-md-content-save", "⤆", "SV", ["actions", "files"]),

  // ── Communication ───────────────────────────────────────────────────────
  define("mail", "nf-md-email", "✉", "@", ["communication"], ["email"]),
  define("mail-open", "nf-md-email-open", "✉", "@@", ["communication"], ["email-open"]),
  define("inbox", "nf-md-inbox", "⌷", "IN", ["communication"]),
  define("send", "nf-md-send", "➤", "->", ["communication"], ["sent"]),
  define("message-circle", "nf-md-message-reply-text", "◌", "[]", ["communication"]),
  define("message-square", "nf-md-message-text", "□", "[]", ["communication"]),
  define("messages", "nf-md-message-processing", "◎□", "[]=", ["communication"]),
  define("chat", "nf-md-chat", "◎", "CH", ["communication"]),
  define("comment", "nf-md-comment", "◈", "CO", ["communication"], ["note"]),
  define("phone", "nf-md-phone", "☎", "PH", ["communication", "devices"]),
  define("phone-call", "nf-md-phone-in-talk", "☎", "PH>", ["communication"]),
  define("phone-incoming", "nf-md-phone-incoming", "↘☎", "PH<", ["communication"]),
  define("phone-outgoing", "nf-md-phone-outgoing", "↗☎", "PH>", ["communication"]),
  define("phone-off", "nf-md-phone-hangup", "⌀", "PHx", ["communication"]),
  define("bell", "nf-md-bell-ring", "♫", "BE", ["communication"], ["notification"]),
  define("bell-off", "nf-md-bell-off", "♪", "BE-", ["communication"], ["notification-off"]),
  define("at-sign", "nf-md-at", "@", "@", ["communication"], ["mention", "tag-user"]),
  define("hash", "nf-md-pound", "#", "#", ["communication"], ["tag", "pound"]),
  define("rss", "nf-md-rss", "⍿", "RS", ["communication"], ["feed"]),
  define("share", "nf-md-share-variant", "⇨", "SH", ["communication", "actions"]),
  define("reply", "nf-md-reply", "↩", "<-", ["communication"], ["respond"]),

  // ── People ──────────────────────────────────────────────────────────────
  define("user", "nf-md-account", "○", "U", ["people"]),
  define("users", "nf-md-account-group", "◎", "UU", ["people"]),
  define("user-plus", "nf-md-account-plus", "○+", "U+", ["people"]),
  define("user-minus", "nf-md-account-minus", "○−", "U-", ["people"]),
  define("user-check", "nf-md-account-check", "○✓", "U✓", ["people"]),
  define("user-x", "nf-md-account-remove", "○×", "Ux", ["people"]),
  define("user-circle", "nf-md-account-circle", "○○", "oU", ["people"]),
  define("contact", "nf-md-card-account-details", "☏", "CT", ["people"]),
  define("contacts", "nf-md-contacts", "☏☏", "CT=", ["people"]),
  define("smile", "nf-md-emoticon-happy", "☺", ":)", ["people"], ["happy", "smiley"]),
  define("frown", "nf-md-emoticon-sad", "☹", ":(", ["people"], ["sad"]),
  define("meh", "nf-md-emoticon-neutral", ":|", ":|", ["people"], ["neutral"]),
  define("baby", "nf-md-baby", "◎", "BB", ["people"]),
  define("person", "nf-md-human", "∣", "/", ["people"], ["human"]),

  // ── Security ────────────────────────────────────────────────────────────
  define("shield", "nf-md-shield-account", "⛨", "S", ["security"], ["protect"]),
  define("shield-check", "nf-md-shield-check", "⛨✓", "S+", ["security"], ["verified"]),
  define("shield-alert", "nf-md-shield-alert", "⛨▲", "S!", ["security"], ["protect-warn"]),
  define("shield-x", "nf-md-shield-remove", "⛨×", "Sx", ["security"], ["protect-off"]),
  define("lock", "nf-md-lock", "⏽", "LK", ["security", "status"], ["locked"]),
  define("unlock", "nf-md-lock-open", "⏼", "LKo", ["security"], ["unlocked"]),
  define("key", "nf-md-key", "⚿", "KY", ["security", "actions"]),
  define("fingerprint", "nf-md-fingerprint", "⊚", "FP", ["security", "devices"]),
  define("eye", "nf-md-eye", "◉", "EY", ["security", "actions"], ["visible", "show"]),
  define("eye-off", "nf-md-eye-off", "◌", "EY-", ["security", "actions"], ["hidden", "hide"]),

  // ── Weather ─────────────────────────────────────────────────────────────
  define("sun", "nf-md-white-balance-sunny", "☀", "SU", ["weather"], ["sunny"]),
  define("moon", "nf-md-moon-waning-crescent", "☾", "MO", ["weather"]),
  define("moon-full", "nf-md-moon-full", "●", "MO", ["weather"]),
  define("cloud", "nf-md-cloud", "☁", "CL", ["weather"]),
  define("cloud-rain", "nf-md-weather-rainy", "⛆", "CL~", ["weather"], ["rain"]),
  define("cloud-snow", "nf-md-weather-snowy", "⛇", "CL*", ["weather"], ["snow"]),
  define("cloud-lightning", "nf-md-weather-lightning", "⛈", "CL!", ["weather"], ["storm", "thunder"]),
  define("cloud-off", "nf-md-cloud-off", "☁×", "CL-", ["weather"]),
  define("umbrella", "nf-md-umbrella", "☂", "UM", ["weather"]),
  define("snowflake", "nf-md-snowflake", "❄", "*", ["weather", "seasons"], ["snow"]),
  define("droplet", "nf-md-water", "∘", "DR", ["weather", "nature"], ["water"]),
  define("wind", "nf-md-weather-windy", "≋", "~~", ["weather"]),
  define("thermometer", "nf-md-thermometer", "⊏", "TH", ["weather"], ["temperature"]),
  define("flame", "nf-md-fire", "∆", "~", ["weather"], ["fire"]),

  // ── Time ────────────────────────────────────────────────────────────────
  define("clock", "nf-md-clock-outline", "◷", "CLK", ["time"]),
  define("alarm", "nf-md-alarm", "⏰", "AL", ["time"]),
  define("timer", "nf-md-timer-outline", "⏳", "TM", ["time"], ["stopwatch"]),
  define("timer-off", "nf-md-timer-off", "⏳×", "TM-", ["time"]),
  define("calendar", "nf-md-calendar", "▦", "[CAL]", ["time"], ["date"]),
  define("calendar-check", "nf-md-calendar-check", "▦✓", "[CAL]+", ["time"]),
  define("calendar-plus", "nf-md-calendar-plus", "▦+", "[CAL]+", ["time"]),
  define("calendar-minus", "nf-md-calendar-remove", "▦−", "[CAL]-", ["time"]),
  define("calendar-x", "nf-md-calendar-remove", "▦×", "[CAL]x", ["time"]),
  define("calendar-days", "nf-md-calendar-month", "▦≡", "[CAL]", ["time"], ["calendar-month"]),
  define("history", "nf-md-history", "↻", "HI", ["time"], ["recent"]),
  define("watch", "nf-md-watch", "⌚", "WA", ["time"]),
  define("hourglass", "nf-md-timer-sand", "⧗", "HG", ["time"], ["timer-sand"]),

  // ── Devices ─────────────────────────────────────────────────────────────
  define("monitor", "nf-md-monitor", "⊡", "PC", ["devices"], ["display", "screen"]),
  define("laptop", "nf-md-laptop", "⊞", "LT", ["devices"]),
  define("tablet", "nf-md-tablet", "◰", "TB", ["devices"]),
  define("smartphone", "nf-md-cellphone", "⊟", "SP", ["devices"], ["phone-mobile", "mobile"]),
  define("tv", "nf-md-television", "▦", "TV", ["devices"], ["television"]),
  define("printer", "nf-md-printer", "⍉", "PR", ["devices"]),
  define("hard-drive", "nf-md-harddisk", "⏚", "HD", ["devices"], ["disk", "storage"]),
  define("cpu", "nf-md-cpu-64-bit", "▥", "CPU", ["devices", "development"]),
  define("chip", "nf-md-chip", "▧", "CHP", ["devices", "development"]),
  define("server", "nf-md-server", "⏣", "SR", ["devices", "development"]),
  define("database", "nf-md-database", "▦", "DB", ["development", "system"]),
  define("wifi", "nf-md-wifi", "⌁", "wifi", ["devices", "connectivity"]),
  define("bluetooth", "nf-md-bluetooth", "⏆", "BT", ["devices", "connectivity"]),
  define("usb", "nf-md-usb", "⏚", "USB", ["devices"]),
  define("keyboard", "nf-md-keyboard", "⌨", "KB", ["devices"]),
  define("mouse", "nf-md-mouse", "⊘", "MS", ["devices"]),
  define("gamepad", "nf-md-gamepad-variant", "⊞", "GP", ["devices", "gaming"], ["controller"]),
  define("camera", "nf-md-camera", "⊙", "CA", ["devices"], ["photo"]),
  define("camera-off", "nf-md-camera-off", "⊙×", "CA-", ["devices"]),

  // ── Development ─────────────────────────────────────────────────────────
  define("terminal", "nf-md-console", ">_", ">_", ["development", "system"], ["console", "shell"]),
  define("code", "nf-md-code-tags", "<>", "<>", ["development"], ["source", "tags"]),
  define("code-2", "nf-md-code-braces", "{}", "{}", ["development"], ["braces"]),
  define("git-branch", "nf-md-source-branch", "⎇", "GB", ["development"], ["branch"]),
  define("git-commit", "nf-md-source-commit", "◉", "GC", ["development"], ["commit"]),
  define("git-merge", "nf-md-source-merge", "⫰", "GM", ["development"], ["merge"]),
  define("git-pull-request", "nf-md-source-pull", "⟷", "GP", ["development"], ["pr", "pull-request"]),
  define("git-compare", "nf-md-source-compare", "↔", "~=", ["development"], ["diff", "compare"]),
  define("bug", "nf-md-bug", "⊗", "BUG", ["development"], ["issue", "insect"]),
  define("bug-off", "nf-md-bug-outline", "⊗×", "BUG-", ["development"]),
  define("lightbulb", "nf-md-lightbulb-on-outline", "☆", "!!", ["development"], ["idea", "insight"]),
  define("lightbulb-off", "nf-md-lightbulb-off-outline", "⬝", "!-", ["development"]),
  define("puzzle", "nf-md-puzzle", "▩", "PZ", ["development"], ["plugin", "extension"]),
  define("webhook", "nf-md-webhook", "↱", "WH", ["development"]),
  define("variable", "nf-md-variable", "x", "VAR", ["development"]),
  define("function", "nf-md-function-variant", "ƒ", "F()", ["development", "math"], ["method", "procedure"]),
  define("package-dev", "nf-md-package-variant-closed", "⏹", "PK", ["development"], ["module"]),
  define("deploy", "nf-md-rocket-launch", "⇧", ">>", ["development"], ["launch"]),

  // ── Brands ──────────────────────────────────────────────────────────────
  define("github", "nf-dev-github", "GH", "GH", ["brands", "development"]),
  define("git", "nf-dev-git", "G", "git", ["brands", "development"]),
  define("docker", "nf-dev-docker", "D", "DK", ["brands", "development"]),
  define("twitter", "nf-md-twitter", "X", "X", ["brands", "communication"]),
  define("facebook", "nf-md-facebook", "f", "FB", ["brands", "communication"]),
  define("instagram", "nf-md-instagram", "⍟", "IG", ["brands", "communication"]),
  define("youtube", "nf-md-youtube", "▶", "YT", ["brands", "media"]),
  define("twitch", "nf-md-twitch", "T", "TV", ["brands", "media"]),
  define("discord", "nf-md-discord", "D", "DC", ["brands", "communication"]),
  define("slack", "nf-md-slack", "#", "SL", ["brands", "communication"]),
  define("linkedin", "nf-md-linkedin", "in", "LN", ["brands", "communication"]),
  define("whatsapp", "nf-md-whatsapp", "W", "WA", ["brands", "communication"]),
  define("reddit", "nf-md-reddit", "R", "RD", ["brands", "communication"]),
  define("npm", "nf-md-npm", "N", "NP", ["brands", "development"]),
  define("nodejs", "nf-dev-nodejs", "N", "ND", ["brands", "development"]),
  define("rust", "nf-dev-rust", "R", "RS", ["brands", "development"]),
  define("python", "nf-dev-python", "P", "PY", ["brands", "development"]),
  define("go", "nf-dev-go", "G", "GO", ["brands", "development"]),
  define("kubernetes", "nf-md-ship-wheel", "K", "K8", ["brands", "development"]),
  define("aws", "nf-dev-aws", "A", "AW", ["brands", "development"]),
  define("google", "nf-dev-google", "G", "GG", ["brands"]),
  define("apple", "nf-dev-apple", "⌘", "AP", ["brands"]),
  define("android", "nf-dev-android", "A", "AN", ["brands", "devices"]),
  define("linux", "nf-dev-linux", "L", "LX", ["brands", "development"]),
  define("windows", "nf-dev-windows", "W", "WN", ["brands"]),
  define("chrome", "nf-dev-chrome", "C", "CH", ["brands"]),
  define("firefox", "nf-dev-firefox", "F", "FF", ["brands"]),
  define("vscode", "nf-dev-visualstudio", "V", "VS", ["brands", "development"]),
  define("figma", "nf-md-drawing", "▤", "FG", ["brands", "design"]),
  define("vercel", "nf-md-triangle", "▲", "VC", ["brands", "development"]),
  define("spotify", "nf-md-spotify", "S", "SP", ["brands", "media"]),
  define("codepen", "nf-dev-codepen", "C", "CP", ["brands", "development"]),
  define("stack-overflow", "nf-dev-stackoverflow", "S", "SO", ["brands", "development"]),

  // ── Shapes ──────────────────────────────────────────────────────────────
  define("circle", "nf-md-circle-outline", "○", "O", ["shapes"]),
  define("circle-filled", "nf-md-circle", "●", "O", ["shapes"]),
  define("square", "nf-md-square-outline", "□", "[]", ["shapes"]),
  define("square-filled", "nf-md-square", "■", "[]", ["shapes"]),
  define("triangle", "nf-md-triangle-outline", "△", "/\\", ["shapes"]),
  define("triangle-filled", "nf-md-triangle", "▲", "/\\", ["shapes"]),
  define("diamond", "nf-md-diamond-outline", "◇", "<>", ["shapes"]),
  define("hexagon", "nf-md-hexagon-outline", "⬡", "HX", ["shapes"]),
  define("octagon", "nf-md-octagon-outline", "⯃", "OC", ["shapes"]),
  define("pentagon", "nf-md-pentagon-outline", "⬠", "PN", ["shapes"]),
  define("star-shape", "nf-md-star-outline", "☆", "*", ["shapes"]),
  define("star-shape-filled", "nf-md-star", "★", "*", ["shapes"]),

  // ── Design ──────────────────────────────────────────────────────────────
  define("pencil", "nf-md-pencil", "✎", "~", ["design", "actions"], ["edit-icon"]),
  define("pen", "nf-md-pen", "✒", "P", ["design", "actions"]),
  define("brush", "nf-md-brush", "∕", "BR", ["design"]),
  define("paint-bucket", "nf-md-format-paint", "⊞", "PB", ["design"], ["fill"]),
  define("palette", "nf-md-palette", "⊚", "PA", ["design"], ["theme", "colors"]),
  define("dropper", "nf-md-eyedropper", "⊘", "DR", ["design"], ["eyedropper", "color-pick"]),
  define("ruler", "nf-md-ruler", "⟝", "RU", ["design"]),
  define("eraser", "nf-md-eraser", "␡", "ER", ["design"]),
  define("frame", "nf-md-image-frame", "⊡", "[]", ["design"]),
  define("image", "nf-md-image", "⊞", "[I]", ["design", "files"], ["picture", "photo"]),
  define("image-plus", "nf-md-image-plus", "⊞+", "[I+]", ["design", "files"]),
  define("grid", "nf-md-grid", "⊞", "[]=", ["design", "layout"]),
  define("columns", "nf-md-view-column", "⊟", "|||", ["design", "layout"]),
  define("rows", "nf-md-view-comfy", "⊞", "===", ["design", "layout"], ["view-list"]),
  define("contrast", "nf-md-contrast-circle", "◐", "CT", ["design"]),

  // ── Buildings ───────────────────────────────────────────────────────────
  define("home", "nf-md-home", "⌂", "H", ["buildings", "navigation"]),
  define("building", "nf-md-office-building", "▥", "BL", ["buildings"]),
  define("building-2", "nf-md-domain", "▦", "BL2", ["buildings"]),
  define("store", "nf-md-store", "▣", "ST", ["buildings", "commerce"]),
  define("warehouse", "nf-md-warehouse", "▩", "WH", ["buildings"]),
  define("factory", "nf-md-factory", "▨", "FC", ["buildings"]),
  define("hotel", "nf-md-bed", "▥", "HT", ["buildings"]),
  define("hospital", "nf-md-hospital-building", "⏥", "HP", ["buildings"]),
  define("school", "nf-md-school", "▥", "SC", ["buildings"]),
  define("church", "nf-md-church", "✝", "CH", ["buildings"]),
  define("castle", "nf-md-castle", "▩", "CA", ["buildings"]),
  define("garage", "nf-md-garage", "▧", "GR", ["buildings"]),
  define("tent", "nf-md-tent", "△", "/\\", ["buildings"]),
  define("bank", "nf-md-bank", "▣", "BK", ["buildings", "commerce"]),
  define("library", "nf-md-library", "▣", "LB", ["buildings"]),

  // ── Transportation ──────────────────────────────────────────────────────
  define("car", "nf-md-car", "⊞", "CR", ["transportation"], ["vehicle"]),
  define("bus", "nf-md-bus", "⊟", "BS", ["transportation"]),
  define("train", "nf-md-train", "⊠", "TR", ["transportation"], ["rail"]),
  define("plane", "nf-md-airplane", "✈", "PL", ["transportation"], ["flight", "airplane"]),
  define("ship", "nf-md-ferry", "⛴", "SH", ["transportation"], ["boat", "ferry"]),
  define("bike", "nf-md-bike", "○", "BK", ["transportation"], ["bicycle"]),
  define("truck", "nf-md-truck", "⊡", "TK", ["transportation"], ["lorry", "delivery"]),
  define("rocket", "nf-md-rocket", "⇧", ">>", ["transportation"], ["spaceship"]),
  define("anchor", "nf-md-anchor", "⚓", "AN", ["transportation"]),
  define("steering-wheel", "nf-md-steering", "◎", "SW", ["transportation"]),

  // ── Commerce ────────────────────────────────────────────────────────────
  define("shopping-cart", "nf-md-cart", "◰", "CRT", ["commerce"], ["cart", "basket"]),
  define("shopping-bag", "nf-md-shopping", "⊞", "BG", ["commerce"], ["bag"]),
  define("package", "nf-md-package-variant-closed", "⏹", "PK", ["commerce"], ["box"]),
  define("credit-card", "nf-md-credit-card", "◰", "CC", ["commerce"], ["card", "payment"]),
  define("wallet", "nf-md-wallet", "⬡", "WL", ["commerce"]),
  define("dollar-sign", "nf-md-currency-usd", "$", "$", ["commerce"], ["money", "currency"]),
  define("banknote", "nf-md-cash", "¤", "CS", ["commerce"], ["cash", "money"]),
  define("receipt", "nf-md-receipt", "▦", "RC", ["commerce"]),
  define("ticket", "nf-md-ticket", "⛭", "TK", ["commerce"]),
  define("tag", "nf-md-tag", "⛁", "T", ["commerce", "status"], ["label"]),

  // ── Health ──────────────────────────────────────────────────────────────
  define("heart-pulse", "nf-md-heart-pulse", "♡~", "<3~", ["health"], ["health", "pulse"]),
  define("activity", "nf-md-pulse", "⎍", "ACT", ["health"]),
  define("pill", "nf-md-pill", "◎", "PL", ["health"]),
  define("bone", "nf-md-bone", "⦿", "BN", ["health"]),
  define("dna", "nf-md-dna", "∞", "DNA", ["health", "science"]),
  define("brain", "nf-md-brain", "◈", "BR", ["health", "science"]),
  define("microscope", "nf-md-microscope", "⏣", "MI", ["health", "science"]),
  define("telescope", "nf-md-telescope", "⏣", "TE", ["science"]),
  define("flask", "nf-md-flask", "∆", "FL", ["science"], ["chemistry", "experiment"]),
  define("atom", "nf-md-atom", "⚛", "AT", ["science"]),
  define("molecule", "nf-md-molecule", "⬡⬡", "ML", ["science"]),

  // ── Food ────────────────────────────────────────────────────────────────
  define("coffee", "nf-md-coffee", "☕", "CF", ["food"]),
  define("pizza", "nf-md-pizza", "◗", "PZ", ["food"]),
  define("apple", "nf-md-food-apple", "◕", "AP", ["food"]),
  define("cake", "nf-md-food-croissant", "◗", "CK", ["food"]),
  define("cookie", "nf-md-cookie", "○", "CK", ["food"]),
  define("glass-cocktail", "nf-md-glass-cocktail", "⊲", "CL", ["food"], ["drink"]),
  define("bottle-wine", "nf-md-bottle-wine", "⊳", "WN", ["food"], ["wine"]),
  define("egg", "nf-md-egg", "○", "EG", ["food"]),
  define("ice-cream", "nf-md-ice-cream", "⊲", "IC", ["food"]),
  define("silverware", "nf-md-silverware", "≡", "SW", ["food"], ["utensils"]),
  define("blender", "nf-md-blender", "⏣", "BL", ["food"]),

  // ── Gaming ──────────────────────────────────────────────────────────────
  define("gamepad-2", "nf-md-gamepad", "⊞", "GP", ["gaming"], ["controller"]),
  define("trophy", "nf-md-trophy", "♛", "TR", ["gaming"], ["winner"]),
  define("medal", "nf-md-medal", "✶", "MD", ["gaming"]),
  define("crown", "nf-md-crown", "♔", "CR", ["gaming"]),
  define("sword", "nf-md-sword", "⚔", "SW", ["gaming"]),
  define("skull", "nf-md-skull", "✝", "SK", ["gaming"]),

  // ── Text ────────────────────────────────────────────────────────────────
  define("bold", "nf-md-format-bold", "B", "B", ["text"]),
  define("italic", "nf-md-format-italic", "I", "/", ["text"]),
  define("underline", "nf-md-format-underline", "U", "_", ["text"]),
  define("strikethrough", "nf-md-format-strikethrough", "S", "-", ["text"]),
  define("code-text", "nf-md-code-tags", "<>", "<>", ["text", "development"]),
  define("quote", "nf-md-format-quote-close", "\"", "\"", ["text"]),
  define("list", "nf-md-format-list-bulleted", "•", "*", ["text"], ["bullet-list"]),
  define("list-ordered", "nf-md-format-list-numbered", "1.", "1.", ["text"], ["numbered-list"]),
  define("list-checks", "nf-md-format-list-checks", "☑", "[x]", ["text"], ["checklist"]),
  define("heading", "nf-md-format-header-1", "H", "H1", ["text"]),
  define("pilcrow", "nf-md-pilcrow", "¶", "P", ["text"]),
  define("text", "nf-md-format-text", "Aa", "T", ["text"]),
  define("align-left", "nf-md-format-align-left", "⫷", "L", ["text", "layout"]),
  define("align-center", "nf-md-format-align-center", "⫸", "C", ["text", "layout"]),
  define("align-right", "nf-md-format-align-right", "⫹", "R", ["text", "layout"]),
  define("align-justify", "nf-md-format-align-justify", "⫺", "J", ["text", "layout"]),

  // ── Math ────────────────────────────────────────────────────────────────
  define("infinity", "nf-md-infinity", "∞", "oo", ["math"]),
  define("sigma", "nf-md-sigma", "Σ", "S", ["math"]),
  define("pi", "nf-md-pi", "π", "PI", ["math"]),
  define("percent", "nf-md-percent", "%", "%", ["math"]),
  define("divide", "nf-md-division", "÷", "/", ["math"]),
  define("equal", "nf-md-equal", "=", "=", ["math"]),
  define("not-equal", "nf-md-not-equal", "≠", "!=", ["math"]),
  define("braces", "nf-md-code-braces", "{}", "{}", ["math"]),

  // ── Accessibility ───────────────────────────────────────────────────────
  define("accessibility", "nf-md-human", "♿", "A11y", ["accessibility"]),
  define("wheelchair", "nf-md-wheelchair-accessibility", "♿", "WC", ["accessibility"]),
  define("ear", "nf-md-ear-hearing", "∮", "EA", ["accessibility"]),

  // ── Connectivity ────────────────────────────────────────────────────────
  define("wifi-off", "nf-md-wifi-off", "⌁×", "wifix", ["connectivity"]),
  define("bluetooth-off", "nf-md-bluetooth-off", "⏆×", "BTx", ["connectivity"]),
  define("airplane-mode", "nf-md-airplane-off", "✈×", "APx", ["connectivity"]),
  define("signal", "nf-md-signal", "▂▄▆█", "~", ["connectivity"]),
  define("battery", "nf-md-battery", "▰", "bat", ["devices", "connectivity"]),
  define("battery-charging", "nf-md-battery-charging", "▰⚡", "bat+", ["devices", "connectivity"]),
  define("battery-full", "nf-md-battery", "▰", "bat", ["devices", "connectivity"]),
  define("battery-low", "nf-md-battery-10", "▱", "bat-", ["devices", "connectivity"]),
  define("power", "nf-md-power", "⏻", "PWR", ["connectivity", "actions"]),
  define("power-off", "nf-md-power-off", "⏼", "PWRx", ["connectivity", "actions"]),

  // ── Layout ──────────────────────────────────────────────────────────────
  define("panel-left", "nf-md-dock-left", "▋", "L|", ["layout"]),
  define("panel-right", "nf-md-dock-right", "▉", "|R", ["layout"]),
  define("panel-top", "nf-md-dock-top", "▀", "T|", ["layout"]),
  define("panel-bottom", "nf-md-dock-bottom", "▄", "|B", ["layout"]),
  define("split-horizontal", "nf-md-dock-window", "▬", "==", ["layout"]),
  define("split-vertical", "nf-md-view-split-vertical", "▮", "||", ["layout"]),
  define("layout-dashboard", "nf-md-view-dashboard", "▤", "[]=", ["layout"]),
  define("layout-grid", "nf-md-view-grid", "⊞", "++", ["layout"]),
  define("layout-list", "nf-md-view-list", "≡", "==", ["layout"]),

  // ── Misc / Utility ──────────────────────────────────────────────────────
  define("search", "nf-md-magnify", "⌕", "?", ["actions", "navigation"], ["find"]),
  define("settings", "nf-md-cog", "⚙", "*", ["actions", "system"], ["preferences", "config"]),
  define("menu", "nf-md-menu", "≡", "=", ["navigation"]),
  define("ellipsis", "nf-md-dots-horizontal", "…", "...", ["actions"]),
  define("ellipsis-vertical", "nf-md-dots-vertical", "⋮", ":", ["actions"]),
  define("log-in", "nf-md-login", "→|", "->", ["actions"], ["login", "sign-in"]),
  define("log-out", "nf-md-logout", "|→", "<-", ["actions"], ["logout", "sign-out"]),
  define("power-icon", "nf-md-power", "⏻", "PWR", ["actions"]),
  define("grip-vertical", "nf-md-drag-vertical", "⋮", ":", ["actions"], ["drag-handle"]),
  define("grip-horizontal", "nf-md-drag-horizontal", "…", "..", ["actions"]),
  define("chef-hat", "nf-md-chef-hat", "◠", "CH", ["food"]),
  define("shield-off", "nf-md-shield-off", "⍟", "S-", ["security"]),
] as const satisfies readonly SemanticIconDefinition[];

export type SemanticIconName = (typeof semanticIcons)[number]["name"];

export const semanticIconMap = new Map<string, SemanticIconDefinition>();
for (const definition of semanticIcons) {
  semanticIconMap.set(definition.name, definition);
  for (const alias of definition.aliases) semanticIconMap.set(alias, definition);
}
